apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-server
  labels:
    app: ssh-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-server
  template:
    metadata:
      labels:
        app: ssh-server
    spec:
      containers:
      - name: ssh-server
        image: ssst0n3/ssh-server
        env:
        - name: PASSWORD_ACCESS
          value: "true"
        - name: USER_NAME
          value: "user"
        - name: USER_PASSWORD
          value: "user"
        ports:
          - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-server
spec:
  type: NodePort
  selector:
    app: ssh-server
  ports:
  - port: 30000
    targetPort: 22
    nodePort: 30000
    protocol: TCP
    name: ssh-server